### ISSUE TITLE
draw_snakesladders()

### ISSUE THREAD

**Issue by dikshasaini11** [dikshasaini11/Group_E_Snakes_and_Ladders#10]
The snakes and ladders are drawn on the board represented by different colors.

**Comment by sayali20773** [comment]
This function has been developed to draw a 10x10 square grid to show board of the game. The layout is displayed in yellow color with numbers starting from 1 to 99. The final winning square(number 100) is displayed with a symbol.

**Comment by sayali20773** [comment]
Added different description.

**Comment by sayali20773** [comment]
This function has been developed to draw snakes and ladders on the game board. Snakes are displayed in red color and ladders are displayed in green color. The positions of ladders and snakes are read from 'snakesladders.dat' file.
